

const Screens = {
     LOGIN_SCREEN:"LOGIN_SCREEN",
     HOME_SCREEN:"HOME_SCREEN",
     ALL_CHATS_SCREEN:"ALL_CHATS_SCREEN",
     CHAT_SCREEN:"CHAT_SCREEN",
     PROFILE_SCREEN:"PROFILE_SCREEN",
     DASHBOARD_SCREEN:"DASHBOARD_SCREEN",
     SEARCH_SCREEN:"SEARCH_SCREEN"
}
export default Screens
