name: Build React Native App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
        run: npm install

  setup-gradle:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build


      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Android Release
        run: |
            cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
            name: app-release.apk
            path: android/app/build/outputs/apk/release/

